config/routes.rb
Fakebook::Application.routes.draw do
  resources :statuses
  
  match 'frontend' => 'frontend#index'
  match 'frontend/:template' => 'frontend#show'

  root to: 'statuses#index'

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content
  
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def index
  end

  def show
    render params[:template]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.order('created_at DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/frontend/index.html.erb
<h1>Frontend#index</h1>
<p>Find me in app/views/frontend/index.html.erb</p>

app/views/frontend/login.html.erb
<section id="banner"><img src="/assets/home-video.jpg" /></section>
    <section id="create-account">
      <h1>Criar Conta</h1>
      <form action="" method="get">
        <div class="form-row">
          <div class="form-label">
            <label class="right inline" for="field-primeiro-nome">Avatar:</label>
          </div>
          <div class="form-field">
            <div class="file upload">
              <div class="fileupload thumbnail" style="width: 40px; height: 40px; float: left; border: 1px solid #ccc;"><img width="40" height="40" src="/assets/user-avatar.png" /></div>
              <input style="float: left; margin: 10px 0 23px 5px;" type="file">
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="form-label">
            <label class="right inline" for="field-primeiro-nome">Primeiro Nome:</label>
          </div>
          <div class="form-field">
            <input id="field-primeiro-nome" tabindex="6" type="text">
          </div>
        </div>
        <div class="form-row">
          <div class="form-label">
            <label class="right inline" for="field-ultimo-nome">Último Nome:</label>
          </div>
          <div class="form-field">
            <input id="field-ultimo-nome" tabindex="7" type="text">
          </div>
        </div>
        <div class="form-row">
          <div class="form-label">
            <label class="right inline" for="field-email-signup">Email:</label>
          </div>
          <div class="form-field">
            <input id="field-email-signup" tabindex="8" type="text">
          </div>
        </div>
        <div class="form-row">
          <div class="form-label">
            <label class="right inline" for="field-password-signup">Senha:</label>
          </div>
          <div class="form-field">
            <input id="field-password-signup" tabindex="9" type="password">
          </div>
        </div>
        <div class="form-row">
          <div class="form-label">
            <label class="right inline" for="field-password-signup">Sexo:</label>
          </div>
          <div class="form-field">
            <select tabindex="10"><option>Selecionar</option></select>
          </div>
        </div>
        <div class="form-row">
          <div class="form-label">
            <label class="right inline" for="field-password-signup">Data de Nascimento:</label>
          </div>
          <div class="form-field">
            <select class="four columns" tabindex="11"><option>Dia</option></select><select class="four columns" tabindex="12"><option>Mês</option></select><select class="four columns" tabindex="13"><option>Ano</option></select>
          </div>
        </div>
        <div class="form-row">
          <div class="form-label"></div>
          <div class="form-field">
            <button class="small button" tabindex="14" type="Submit">Criar Conta</button>
          </div>
        </div>
      </form>
    </section>

app/views/frontend/post_details.html.erb
<section id="news-feed-nav">
      <div class="welcome-box">
        <a href="/news-feed">
          <div class="user-avatar">
            <div class="user-avatar-inner"><img width="40" height="40" src="/assets/user-chuck.jpg" /></div>
          </div>
          <div class="user-name">Chuck Norris</div>
        </a>
      </div>
    </section><section id="post-details">
      <div class="box">
        <header class="box-header">
          <h1>Detalhes Post</h1>
        </header>
        <div class="box-content">
          <div class="list-view ui-comments-list">
            <ul>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-chuck.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Chuck Norris</a>
                    </div>
                    <div class="user-comment">
                      <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

app/views/frontend/show.html.erb
<h1>Frontend#show</h1>
<p>Find me in app/views/frontend/show.html.erb</p>

app/views/frontend/statuses.html.erb
<section id="news-feed-nav">
      <div class="welcome-box">
        <a href="/news-feed">
          <div class="user-avatar">
            <div class="user-avatar-inner"><img width="40" height="40" src="/assets/user-chuck.jpg" /></div>
          </div>
          <div class="user-name">Chuck Norris</div>
        </a>
      </div>
    </section><section id="news-feed">
      <div class="box">
        <header class="box-header"><a class="button" href="update-status">Atualizar Status</a></header>
        <div class="box-content">
          <div class="list-view ui-comments-list">
            <ul>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-chuck.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Chuck Norris</a>
                    </div>
                    <div class="user-comment">
                      <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-rafael.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Rafael Torales</a>
                    </div>
                    <div class="user-comment">
                      <p>Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-mclovin.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Mc Lovin</a>
                    </div>
                    <div class="user-comment">
                      <p>Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-chuck.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Chuck Norris</a>
                    </div>
                    <div class="user-comment">
                      <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-chuck.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Chuck Norris</a>
                    </div>
                    <div class="user-comment">
                      <p>Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim.</p>
                      <p><img src="/assets/wall-chuck-norris.jpeg" /></p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-mclovin.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Mc Lovin</a>
                    </div>
                    <div class="user-comment">
                      <p>Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-rafael.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Rafael Torales</a>
                    </div>
                    <div class="user-comment">
                      <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-chuck.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Chuck Norris</a>
                    </div>
                    <div class="user-comment">
                      <p>Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">26</a></span><span class="count-comments"><a href="#">100</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="item-image usuario">
                  <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-chuck.jpg" /></span>
                </div>
                <div class="item-info">
                  <div class="item-activity">
                    <div class="user-name">
                      <a href="/profile">Chuck Norris</a>
                    </div>
                    <div class="user-comment">
                      <p>Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.</p>
                    </div>
                    <div class="item-actions">
                      <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp"><time class="js-timeago" datetime="">20 de Setembro</time></span>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <title>Fakebook - News Feed</title>
    <link href="/images/favicon.png" rel="icon" type="image/png" />
    <link href="/images/favicon.ico" rel="shortcut icon" />
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="index">
    <header id="header" role="banner">
      <div id="header-inner">
        <div id="logo">
          <a href="/" title="Fakebook">Fakebook</a>
        </div>
        <div id="user-login">
          <form action="" method="get">
            <div class="user-login-email">
              <label for="field-email">Email</label><input id="field-email" tabindex="1" type="text">
            </div>
            <div class="user-login-password">
              <label for="field-password">Senha</label><input id="field-password" tabindex="2" type="password"><a class="text" href="#" tabindex="4">Esqueceu sua senha?</a>
            </div>
            <div class="user-login-actions">
              <button class="small button" tabindex="3" type="Submit">Entrar</button>
            </div>
          </form>
        </div>
        <!--end #user-login-->
		
		<!-- <nav class="nav-user" role="navigation">
		          <ul>
		            <li class="item-avatar">
		              <div class="user-avatar small">
		                <div class="user-avatar-inner"><img width="24" height="24" src="../images/user-chuck.jpg" /></div>
		              </div>
		            </li>
		            <li class="item-username"><a href="/edit-profile" title="Minha Conta"><b>Chuck Norris</b></a></li>
		            <li class="item-logout"><a href="/">Sair</a></li>
		          </ul>
		        </nav> -->
        <!--end .nav-user-->
        


      </div>
      <!--end #header-inner-->
	</header>

   

    <div id="content">
      <div id="content-inner">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "erro") %> não permitiu que esse arquivo seja salvo:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<section id="news-feed-nav">
  <div class="welcome-box">
    <a href="/news-feed"></a>
    <div class="user-avatar">
      <div class="user-avatar-inner">
        <img width="40" height="40" src="/assets/user-chuck.jpg" />
      </div>
    </div>
    <div class="user-name">
      Chuck Norris
    </div>
  </div>
</section>

<section id="news-feed">
  <div class="box">
    
    <header class="box-header">
      <%= link_to 'Atualizar Status', new_status_path, class: 'button' %>
    </header>
    
    <div class="box-content">
      <div class="list-view ui-comments-list">
        <ul>
          <% @statuses.each do |status| %>
          <li>
            <div class="item-image usuario">
              <span class="item-image-wrap"><img width="40" height="40" src="/assets/user-chuck.jpg" /></span>
            </div>
            <div class="item-info">
              <div class="item-activity">
                <div class="user-name">
                  <a href="/profile">Chuck Norris</a>
                </div>
                <div class="user-comment">
                  <%= simple_format(status.content) %>
                </div>
                <div class="item-actions">
                  <span class="action-like"><a href="#">Curtir</a></span><span class="action-comment"><a href="#">Comentar</a></span><span class="count-likes"><a href="#">2</a></span><span class="count-comments"><a href="#">0</a></span><span class="timestamp">20 de Setembro</span>
                </div>
              </div>
            </div>
            <%= link_to 'Show', status %>
            <%= link_to 'Edit', edit_status_path(status) %>
            <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>